# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "manager" do |node|
    node.vm.hostname = "manager"
    node.vm.box = "bento/ubuntu-18.04"
    node.vm.network "private_network", ip: "192.168.16.73"

    # Opsional. Edit sesuai dengan nama network adapter di komputer
    # node.vm.network "public_network", bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"
      
    node.vm.provider "virtualbox" do |vb|
      vb.name = "manager"
      vb.gui = false
      vb.memory = "512"
    end

    node.vm.provision "shell", path: "provision/manager_bootstrap.sh", privileged: false
  end

  (1..3).each do |i|
    config.vm.define "service#{i}" do |node|
      node.vm.hostname = "service#{i}"
      node.vm.box = "bento/ubuntu-18.04"
      id = 73+i
      node.vm.network "private_network", ip: "192.168.16.#{id}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "service#{i}"
        vb.gui = false
        vb.memory = "512"
      end

      node.vm.provision "shell", path: "provision/service_bootstrap.sh", privileged: false
    end
  end

  (1..3).each do |i|
    config.vm.define "data#{i}" do |node|
      node.vm.hostname = "data#{i}"
      node.vm.box = "bento/ubuntu-18.04"
      id = 76+i
      node.vm.network "private_network", ip: "192.168.16.#{id}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "data#{i}"
        vb.gui = false
        vb.memory = "768"
      end

      node.vm.provision "shell", path: "provision/data_bootstrap.sh", privileged: false
    end
  end


end
